"""
data.py — Static content: subject metadata, curated YouTube resources,
and the pre-written question bank used before any AI refresh.
"""

# ══════════════════════════════════════════════════════════════════════════════
# SUBJECT DATA
# ══════════════════════════════════════════════════════════════════════════════
SUBJECT_DATA = {
    "History":          {"icon": "📜", "desc": "India & the world"},
    "Geography":        {"icon": "🌍", "desc": "India, planets & beyond"},
    "Politics":         {"icon": "🏛️", "desc": "Civics and governance"},
    "Biology":          {"icon": "🔬", "desc": "Life & living systems"},
    "Computer Science": {"icon": "💻", "desc": "Coding & technology"},
    "English":          {"icon": "📖", "desc": "Grammar & vocabulary"},

# ══════════════════════════════════════════════════════════════════════════════
# YOUTUBE STUDY RESOURCES  (shown on result page)
# ══════════════════════════════════════════════════════════════════════════════
}

# ══════════════════════════════════════════════════════════════════════════════
# YOUTUBE STUDY RESOURCES  (shown on result page)
# ══════════════════════════════════════════════════════════════════════════════
YOUTUBE_RESOURCES = {
    "History": [
        {"icon": "🏛️", "title": "India's Full History",         "desc": "Ancient to Modern India — complete playlist",           "url": "https://www.youtube.com/results?search_query=history+of+india+full+course+hindi+english",          "tag": "Full Course"},
        {"icon": "🌍", "title": "World History Explained",       "desc": "Key world events & civilisations",                      "url": "https://www.youtube.com/results?search_query=world+history+documentary+explained",                   "tag": "World"},
        {"icon": "⚔️",  "title": "Freedom Struggle",              "desc": "India's independence movement deep-dive",               "url": "https://www.youtube.com/results?search_query=india+freedom+struggle+independence+movement",           "tag": "India"},
        {"icon": "📺", "title": "History GK for Exams",          "desc": "Quick-revision MCQs for competitive exams",             "url": "https://www.youtube.com/results?search_query=history+gk+questions+competitive+exam+preparation",      "tag": "Exam Prep"},
    ],
    "Geography": [
        {"icon": "🗺️", "title": "Indian Geography Masterclass",  "desc": "Rivers, mountains, climate — full overview",            "url": "https://www.youtube.com/results?search_query=indian+geography+full+course+upsc",                      "tag": "India"},
        {"icon": "🌐", "title": "World Geography in Hindi/Eng",   "desc": "Continents, oceans & physical geography",               "url": "https://www.youtube.com/results?search_query=world+geography+full+course+explained",                   "tag": "World"},
        {"icon": "🪐", "title": "Solar System & Space",           "desc": "Planets, orbits and our universe",                     "url": "https://www.youtube.com/results?search_query=solar+system+planets+explained+for+students",             "tag": "Space"},
        {"icon": "📊", "title": "Geography MCQs",                 "desc": "Practice questions for exams",                         "url": "https://www.youtube.com/results?search_query=geography+mcq+quiz+exam+preparation",                     "tag": "Exam Prep"},
    ],
    "Politics": [
        {"icon": "📜", "title": "Indian Polity by Laxmikant",    "desc": "Constitution, Parliament & governance explained",       "url": "https://www.youtube.com/results?search_query=indian+polity+laxmikant+upsc+complete+course",            "tag": "Full Course"},
        {"icon": "⚖️",  "title": "Fundamental Rights & Duties",   "desc": "Articles, amendments & judgements",                    "url": "https://www.youtube.com/results?search_query=fundamental+rights+duties+indian+constitution+explained",  "tag": "Constitution"},
        {"icon": "🏛️", "title": "Parliament & Elections",         "desc": "How Indian democracy works",                           "url": "https://www.youtube.com/results?search_query=indian+parliament+election+commission+explained",           "tag": "Democracy"},
        {"icon": "🎯", "title": "Polity MCQs for Exams",          "desc": "Quick revision with practice questions",               "url": "https://www.youtube.com/results?search_query=indian+polity+mcq+exam+preparation+quiz",                 "tag": "Exam Prep"},
    ],
    "Biology": [
        {"icon": "🔬", "title": "Cell Biology Full Course",       "desc": "Cell structure, organelles & processes",               "url": "https://www.youtube.com/results?search_query=cell+biology+full+course+for+students",                   "tag": "Full Course"},
        {"icon": "🧬", "title": "Genetics & DNA Explained",       "desc": "Heredity, genes, DNA replication",                     "url": "https://www.youtube.com/results?search_query=genetics+DNA+replication+explained+biology",              "tag": "Genetics"},
        {"icon": "🫀", "title": "Human Body Systems",             "desc": "Digestive, respiratory, circulatory & more",           "url": "https://www.youtube.com/results?search_query=human+body+systems+biology+explained+for+students",       "tag": "Human Body"},
        {"icon": "🌿", "title": "Photosynthesis & Respiration",   "desc": "Plant biology & metabolic pathways",                   "url": "https://www.youtube.com/results?search_query=photosynthesis+cellular+respiration+explained+biology",    "tag": "Plants"},
    ],
    "Computer Science": [
        {"icon": "💻", "title": "Python for Beginners",           "desc": "Complete Python programming from scratch",             "url": "https://www.youtube.com/results?search_query=python+programming+full+course+beginners",                 "tag": "Programming"},
        {"icon": "🌐", "title": "Data Structures & Algorithms",   "desc": "Arrays, trees, sorting — with examples",               "url": "https://www.youtube.com/results?search_query=data+structures+algorithms+full+course",                  "tag": "DSA"},
        {"icon": "🖥️", "title": "How Computers Work",             "desc": "CPU, memory, OS fundamentals explained",               "url": "https://www.youtube.com/results?search_query=how+computers+work+CPU+memory+operating+system",           "tag": "Fundamentals"},
        {"icon": "🔐", "title": "Cybersecurity Basics",           "desc": "Networks, security & the internet",                    "url": "https://www.youtube.com/results?search_query=cybersecurity+basics+networking+fundamentals+explained",    "tag": "Security"},
    ],
    "English": [
        {"icon": "📝", "title": "English Grammar Mastery",        "desc": "Tenses, parts of speech, sentence structure",          "url": "https://www.youtube.com/results?search_query=english+grammar+full+course+beginners",                   "tag": "Grammar"},
        {"icon": "📚", "title": "Vocabulary Builder",             "desc": "1000+ words with meaning & usage",                    "url": "https://www.youtube.com/results?search_query=english+vocabulary+building+words+meaning+usage",          "tag": "Vocabulary"},
        {"icon": "🗣️", "title": "Spoken English Fluency",         "desc": "Speaking naturally with confidence",                   "url": "https://www.youtube.com/results?search_query=spoken+english+fluency+course+for+beginners",             "tag": "Speaking"},
        {"icon": "✍️",  "title": "Essay & Writing Skills",         "desc": "Writing structured essays & paragraphs",               "url": "https://www.youtube.com/results?search_query=english+essay+writing+skills+for+students",              "tag": "Writing"},
    ],

# ══════════════════════════════════════════════════════════════════════════════
# PRE-WRITTEN QUESTIONS  (used by default; refreshed by AI on demand)
# ══════════════════════════════════════════════════════════════════════════════
}

# ══════════════════════════════════════════════════════════════════════════════
# PRE-WRITTEN QUESTIONS  (used by default; refreshed by AI on demand)
# ══════════════════════════════════════════════════════════════════════════════
PRESET_QUESTIONS = {
    "History": {
        "Easy": [
            {"question": "Who was the first Prime Minister of independent India?", "options": {"A": "Mahatma Gandhi", "B": "Sardar Patel", "C": "Jawaharlal Nehru", "D": "B.R. Ambedkar"}, "answer": "C", "explanation": "Jawaharlal Nehru became India's first Prime Minister on 15 August 1947. He served until his death in May 1964."},
            {"question": "In which year did India gain independence from British rule?", "options": {"A": "1945", "B": "1946", "C": "1947", "D": "1948"}, "answer": "C", "explanation": "India gained independence on 15 August 1947 after decades of struggle. The Indian Independence Act was passed by the British Parliament in July 1947."},
            {"question": "Who built the Taj Mahal?", "options": {"A": "Akbar", "B": "Humayun", "C": "Aurangzeb", "D": "Shah Jahan"}, "answer": "D", "explanation": "Mughal Emperor Shah Jahan built the Taj Mahal in memory of his beloved wife Mumtaz Mahal. It was completed around 1653 AD."},
            {"question": "The Sepoy Mutiny (First War of Independence) took place in which year?", "options": {"A": "1847", "B": "1857", "C": "1867", "D": "1877"}, "answer": "B", "explanation": "The Sepoy Mutiny of 1857, also called India's First War of Independence, began in Meerut on 10 May 1857. It was a major revolt against British East India Company rule."},
            {"question": "Which country colonised India before independence?", "options": {"A": "France", "B": "Portugal", "C": "Netherlands", "D": "Britain"}, "answer": "D", "explanation": "Britain, through the British East India Company, gradually colonised India and by 1858 the British Crown took direct control. British rule in India is often called the 'Raj'."},
        ],
        "Medium": [
            {"question": "In which year was the Indian National Congress founded?", "options": {"A": "1875", "B": "1885", "C": "1895", "D": "1905"}, "answer": "B", "explanation": "The Indian National Congress was founded on 28 December 1885 in Bombay, with A.O. Hume as its founder. It became the principal political party leading the independence movement."},
            {"question": "The Partition of Bengal in 1905 was announced by which Viceroy?", "options": {"A": "Lord Dalhousie", "B": "Lord Curzon", "C": "Lord Mountbatten", "D": "Lord Wavell"}, "answer": "B", "explanation": "Lord Curzon, the Viceroy of India, announced the Partition of Bengal in 1905. The partition aroused intense nationalist feelings and led to the Swadeshi Movement."},
            {"question": "The Jallianwala Bagh massacre (1919) took place in which city?", "options": {"A": "Delhi", "B": "Lahore", "C": "Amritsar", "D": "Lucknow"}, "answer": "C", "explanation": "The Jallianwala Bagh massacre occurred on 13 April 1919 in Amritsar, Punjab. General Dyer ordered troops to fire on unarmed civilians, killing hundreds."},
            {"question": "Who wrote the book 'The Discovery of India'?", "options": {"A": "Mahatma Gandhi", "B": "Jawaharlal Nehru", "C": "Rabindranath Tagore", "D": "Sardar Patel"}, "answer": "B", "explanation": "Jawaharlal Nehru wrote 'The Discovery of India' while imprisoned at Ahmednagar Fort (1942-1945). The book explores India's history, culture, and philosophy."},
            {"question": "The Battle of Plassey (1757) was fought between the British and whom?", "options": {"A": "The Mughals", "B": "The Marathas", "C": "The Nawab of Bengal", "D": "The Sultan of Mysore"}, "answer": "C", "explanation": "The Battle of Plassey on 23 June 1757 was fought between the British East India Company and Siraj ud-Daulah, the Nawab of Bengal. The British victory laid the foundation of British rule in India."},
        ],
        "Hard": [
            {"question": "Which session of the Indian National Congress passed the resolution for complete independence (Purna Swaraj)?", "options": {"A": "Calcutta 1928", "B": "Lahore 1929", "C": "Karachi 1931", "D": "Lucknow 1936"}, "answer": "B", "explanation": "The Lahore session of the INC in December 1929, presided by Jawaharlal Nehru, declared Purna Swaraj (complete independence) as its goal. 26 January was chosen as Independence Day from 1930 onwards."},
            {"question": "The Simon Commission was boycotted by Indian leaders mainly because:", "options": {"A": "It recommended partition of India", "B": "It had no Indian members", "C": "It proposed new tax laws", "D": "It restricted electoral rights"}, "answer": "B", "explanation": "The Simon Commission (1928) consisted entirely of British members with no Indian representation. This was deeply insulting to Indians and led to widespread protests with the slogan 'Simon Go Back'."},
            {"question": "Who founded the Azad Hind Fauj (Indian National Army)?", "options": {"A": "Bhagat Singh", "B": "Bal Gangadhar Tilak", "C": "Subhas Chandra Bose", "D": "Lala Lajpat Rai"}, "answer": "C", "explanation": "Subhas Chandra Bose reorganised and led the Indian National Army (Azad Hind Fauj) during World War II. He aimed to liberate India from British rule with Japanese support."},
            {"question": "Which Act transferred governing power in India from the East India Company to the British Crown?", "options": {"A": "Regulating Act 1773", "B": "Charter Act 1853", "C": "Government of India Act 1858", "D": "Indian Councils Act 1861"}, "answer": "C", "explanation": "The Government of India Act 1858 was passed following the 1857 revolt. It dissolved the East India Company and transferred all powers to the British Crown, establishing direct Crown rule."},
            {"question": "The Treaty of Versailles (1919), which ended World War I, imposed heavy reparations on which country?", "options": {"A": "Austria", "B": "Germany", "C": "Ottoman Empire", "D": "Hungary"}, "answer": "B", "explanation": "The Treaty of Versailles placed full blame for WWI on Germany through the 'War Guilt Clause' (Article 231). Germany was required to pay massive reparations, which contributed to economic instability and the rise of Nazism."},
        ],
    },
    "Geography": {
        "Easy": [
            {"question": "What is the capital city of India?", "options": {"A": "Mumbai", "B": "Kolkata", "C": "New Delhi", "D": "Chennai"}, "answer": "C", "explanation": "New Delhi is the capital city of India and serves as the seat of all three branches of the Indian government. It was officially declared capital in 1911, replacing Calcutta."},
            {"question": "Which is the longest river in India?", "options": {"A": "Yamuna", "B": "Godavari", "C": "Brahmaputra", "D": "Ganga"}, "answer": "D", "explanation": "The Ganga (Ganges) is the longest river in India, stretching approximately 2,525 km. It originates from the Gangotri glacier in the Himalayas and flows into the Bay of Bengal."},
            {"question": "On which continent is the Sahara Desert located?", "options": {"A": "Asia", "B": "Australia", "C": "Africa", "D": "South America"}, "answer": "C", "explanation": "The Sahara is the world's largest hot desert, located across North Africa. It spans about 9 million square kilometres, covering much of North Africa."},
            {"question": "What is the capital of France?", "options": {"A": "Berlin", "B": "Madrid", "C": "Rome", "D": "Paris"}, "answer": "D", "explanation": "Paris is the capital and largest city of France, located along the Seine River. It is known as the 'City of Light' and is famous for landmarks like the Eiffel Tower."},
            {"question": "Which planet is closest to the Sun?", "options": {"A": "Venus", "B": "Earth", "C": "Mars", "D": "Mercury"}, "answer": "D", "explanation": "Mercury is the closest planet to the Sun in our solar system, orbiting at an average distance of about 57.9 million km. It completes one orbit around the Sun every 88 Earth days."},
        ],
        "Medium": [
            {"question": "What is the largest ocean on Earth by area?", "options": {"A": "Atlantic Ocean", "B": "Indian Ocean", "C": "Arctic Ocean", "D": "Pacific Ocean"}, "answer": "D", "explanation": "The Pacific Ocean is the largest and deepest ocean on Earth, covering about 165 million square kilometres. It accounts for approximately 46% of Earth's water surface area."},
            {"question": "What is the capital of Australia?", "options": {"A": "Sydney", "B": "Melbourne", "C": "Canberra", "D": "Perth"}, "answer": "C", "explanation": "Canberra is the capital city of Australia and home to the national government. It was purpose-built as a compromise between rivals Sydney and Melbourne, and was inaugurated as the capital in 1913."},
            {"question": "The Radcliffe Line forms the border between which two countries?", "options": {"A": "India and Nepal", "B": "India and China", "C": "India and Pakistan", "D": "India and Bangladesh"}, "answer": "C", "explanation": "The Radcliffe Line, drawn by Sir Cyril Radcliffe in 1947, forms the border between India and Pakistan. It was created during the partition of the Indian subcontinent."},
            {"question": "Which is the largest desert in the world by total area?", "options": {"A": "Sahara Desert", "B": "Arabian Desert", "C": "Gobi Desert", "D": "Antarctic Desert"}, "answer": "D", "explanation": "The Antarctic Desert is the world's largest desert with an area of about 14 million sq km. A desert is defined by low precipitation, and Antarctica receives less than 200mm of rain equivalent per year."},
            {"question": "The Strait of Malacca connects which two bodies of water?", "options": {"A": "Red Sea and Arabian Sea", "B": "South China Sea and Andaman Sea", "C": "Pacific and Indian Oceans", "D": "Java Sea and Indian Ocean"}, "answer": "B", "explanation": "The Strait of Malacca runs between the Malay Peninsula and Sumatra, connecting the South China Sea to the Andaman Sea. It is one of the world's most important shipping lanes."},
        ],
        "Hard": [
            {"question": "What is the latitude of the Tropic of Cancer?", "options": {"A": "0 degrees (Equator)", "B": "23.5 degrees N", "C": "66.5 degrees N", "D": "23.5 degrees S"}, "answer": "B", "explanation": "The Tropic of Cancer is at approximately 23.5 North latitude. It is the northernmost circle of latitude where the Sun can be directly overhead, which occurs at the June solstice."},
            {"question": "Which country has the greatest number of freshwater lakes in the world?", "options": {"A": "Russia", "B": "USA", "C": "Canada", "D": "Brazil"}, "answer": "C", "explanation": "Canada holds approximately 60% of the world's lakes, with an estimated 2 million lakes covering about 9% of its territory. This is largely a result of glaciation during the last Ice Age."},
            {"question": "What is the deepest lake in the world?", "options": {"A": "Lake Superior", "B": "Caspian Sea", "C": "Lake Titicaca", "D": "Lake Baikal"}, "answer": "D", "explanation": "Lake Baikal in Siberia, Russia, is the world's deepest lake at approximately 1,642 metres deep. It also holds about 20% of the world's unfrozen surface fresh water."},
            {"question": "Which river forms a major part of the border between the USA and Mexico?", "options": {"A": "Colorado River", "B": "Mississippi River", "C": "Rio Grande", "D": "Missouri River"}, "answer": "C", "explanation": "The Rio Grande forms the international border between the US state of Texas and the Mexican states of Chihuahua, Coahuila, Nuevo Leon and Tamaulipas. It flows approximately 3,057 km in total."},
            {"question": "The Mariana Trench, the deepest point on Earth, is located in which ocean?", "options": {"A": "Atlantic Ocean", "B": "Indian Ocean", "C": "Arctic Ocean", "D": "Pacific Ocean"}, "answer": "D", "explanation": "The Mariana Trench is located in the western Pacific Ocean and reaches a maximum depth of about 11,034 metres at a point called Challenger Deep. It is deeper than Mount Everest is tall."},
        ],
    },
    "Politics": {
        "Easy": [
            {"question": "Who is the constitutional head of the Republic of India?", "options": {"A": "Prime Minister", "B": "Chief Justice of India", "C": "President", "D": "Speaker of Lok Sabha"}, "answer": "C", "explanation": "The President of India is the constitutional head of state. However, in practice, executive power is exercised by the Prime Minister and the Council of Ministers, making it a parliamentary democracy."},
            {"question": "The Indian Constitution came into force on:", "options": {"A": "15 August 1947", "B": "26 November 1949", "C": "26 January 1950", "D": "2 October 1949"}, "answer": "C", "explanation": "The Constitution of India came into effect on 26 January 1950, which is celebrated as Republic Day. It was adopted by the Constituent Assembly on 26 November 1949."},
            {"question": "How many original articles did the Indian Constitution have?", "options": {"A": "256", "B": "350", "C": "395", "D": "448"}, "answer": "C", "explanation": "The original Indian Constitution had 395 articles, 22 parts, and 8 schedules. Today, due to amendments, it has grown to over 448 articles and 12 schedules."},
            {"question": "What does the Preamble of the Indian Constitution declare India to be?", "options": {"A": "A Federal Democratic Republic", "B": "A Parliamentary Democracy", "C": "A Sovereign Socialist Secular Democratic Republic", "D": "A Constitutional Monarchy"}, "answer": "C", "explanation": "The Preamble declares India to be a Sovereign, Socialist, Secular, Democratic Republic. The words 'Socialist' and 'Secular' were added by the 42nd Amendment in 1976."},
            {"question": "Which body has the power to amend the Indian Constitution?", "options": {"A": "Supreme Court", "B": "The President of India", "C": "Parliament", "D": "Lok Sabha alone"}, "answer": "C", "explanation": "Under Article 368, Parliament has the power to amend the Constitution. However, certain provisions require ratification by at least half of the state legislatures as well."},
        ],
        "Medium": [
            {"question": "The concept of Judicial Review in India is primarily borrowed from:", "options": {"A": "United Kingdom", "B": "United States of America", "C": "Canada", "D": "Australia"}, "answer": "B", "explanation": "The concept of Judicial Review, which allows courts to review legislation for constitutional validity, was borrowed from the USA. It was incorporated into the Indian Constitution to protect fundamental rights."},
            {"question": "Which Article of the Indian Constitution abolishes untouchability?", "options": {"A": "Article 14", "B": "Article 17", "C": "Article 19", "D": "Article 21"}, "answer": "B", "explanation": "Article 17 of the Indian Constitution abolishes untouchability and forbids its practice in any form. The Protection of Civil Rights Act 1955 enforces this constitutional provision."},
            {"question": "The 73rd Constitutional Amendment Act (1992) is related to:", "options": {"A": "Right to Education", "B": "Anti-defection Law", "C": "Panchayati Raj System", "D": "Reservation in Government Jobs"}, "answer": "C", "explanation": "The 73rd Amendment gave constitutional status to Panchayati Raj institutions (local self-government in rural areas). It added the 11th Schedule and introduced elections to these bodies."},
            {"question": "The word 'Secular' was added to the Preamble of the Indian Constitution by which Amendment?", "options": {"A": "44th Amendment", "B": "52nd Amendment", "C": "42nd Amendment", "D": "46th Amendment"}, "answer": "C", "explanation": "The 42nd Constitutional Amendment Act (1976), enacted during the Emergency, added both 'Socialist' and 'Secular' to the Preamble. This amendment is sometimes called the 'Mini-Constitution'."},
            {"question": "Who chaired the Drafting Committee of the Indian Constitution?", "options": {"A": "Jawaharlal Nehru", "B": "Rajendra Prasad", "C": "Sardar Patel", "D": "B.R. Ambedkar"}, "answer": "D", "explanation": "Dr. B.R. Ambedkar chaired the seven-member Drafting Committee of the Constituent Assembly. He is widely regarded as the principal architect of the Indian Constitution."},
        ],
        "Hard": [
            {"question": "Which Article of the Indian Constitution deals with the power to proclaim a National Emergency?", "options": {"A": "Article 352", "B": "Article 356", "C": "Article 360", "D": "Article 370"}, "answer": "A", "explanation": "Article 352 empowers the President to proclaim a National Emergency if the security of India is threatened by war, external aggression, or armed rebellion. Article 356 deals with State Emergency (President's Rule)."},
            {"question": "The landmark Kesavananda Bharati case (1973) established which constitutional doctrine?", "options": {"A": "Doctrine of Separation of Powers", "B": "Doctrine of Judicial Activism", "C": "Basic Structure Doctrine", "D": "Rule of Law Doctrine"}, "answer": "C", "explanation": "In Kesavananda Bharati v. State of Kerala (1973), the Supreme Court held that Parliament cannot amend the 'basic structure' of the Constitution. This doctrine limits parliamentary power to amend the Constitution."},
            {"question": "The Directive Principles of State Policy in the Indian Constitution are borrowed from which country's constitution?", "options": {"A": "USA", "B": "USSR", "C": "Canada", "D": "Ireland"}, "answer": "D", "explanation": "The Directive Principles of State Policy (Part IV, Articles 36-51) are borrowed from the Irish Constitution of 1937. They are non-justiciable but fundamental in governance."},
            {"question": "The anti-defection provisions in India are contained in which Schedule of the Constitution?", "options": {"A": "8th Schedule", "B": "9th Schedule", "C": "10th Schedule", "D": "12th Schedule"}, "answer": "C", "explanation": "The 10th Schedule, added by the 52nd Amendment (1985), contains the anti-defection law. It disqualifies members of Parliament or state legislatures who defect from their political party."},
            {"question": "Under which Article can the President of India refer a question of law or fact to the Supreme Court for its opinion?", "options": {"A": "Article 131", "B": "Article 136", "C": "Article 143", "D": "Article 148"}, "answer": "C", "explanation": "Article 143 grants the President the power to consult the Supreme Court by referring questions of law or public importance (Advisory Jurisdiction). The Supreme Court may or may not answer such a reference."},
        ],
    },
    "Biology": {
        "Easy": [
            {"question": "Which organelle is known as the 'powerhouse of the cell'?", "options": {"A": "Nucleus", "B": "Ribosome", "C": "Mitochondria", "D": "Cell Membrane"}, "answer": "C", "explanation": "The mitochondria produce ATP (adenosine triphosphate) through the process of cellular respiration, providing energy for cellular activities. This is why they are called the powerhouse of the cell."},
            {"question": "How many chromosomes does a normal human body cell have?", "options": {"A": "23", "B": "44", "C": "46", "D": "48"}, "answer": "C", "explanation": "Human body cells contain 46 chromosomes arranged in 23 pairs. Reproductive cells (sperm and eggs) contain only 23 chromosomes, combining to form 46 at fertilisation."},
            {"question": "What is the process by which plants make their own food using sunlight?", "options": {"A": "Respiration", "B": "Transpiration", "C": "Digestion", "D": "Photosynthesis"}, "answer": "D", "explanation": "Photosynthesis is the process where plants use sunlight, carbon dioxide, and water to produce glucose and oxygen. The reaction occurs in chloroplasts using the green pigment chlorophyll."},
            {"question": "Which is the largest organ of the human body?", "options": {"A": "Heart", "B": "Liver", "C": "Brain", "D": "Skin"}, "answer": "D", "explanation": "The skin is the largest organ of the human body, covering an area of about 1.5-2 square metres in adults. It acts as a protective barrier, regulates temperature, and contains sensory receptors."},
            {"question": "What determines a person's blood type (A, B, AB or O)?", "options": {"A": "Antibodies in plasma", "B": "Antigens on red blood cell surface", "C": "White blood cell count", "D": "Enzymes in blood"}, "answer": "B", "explanation": "Blood type is determined by specific antigens (proteins) present on the surface of red blood cells. The ABO blood grouping system and the Rh factor together determine a person's blood type."},
        ],
        "Medium": [
            {"question": "Which organelle is primarily responsible for protein synthesis?", "options": {"A": "Mitochondria", "B": "Nucleus", "C": "Ribosome", "D": "Golgi Apparatus"}, "answer": "C", "explanation": "Ribosomes are the sites of protein synthesis (translation) in the cell. They read messenger RNA (mRNA) sequences and assemble amino acids into polypeptide chains according to the genetic code."},
            {"question": "The modern science of genetics was pioneered by:", "options": {"A": "Charles Darwin", "B": "Gregor Mendel", "C": "Louis Pasteur", "D": "Robert Hooke"}, "answer": "B", "explanation": "Gregor Mendel, an Austrian monk, pioneered genetics through his experiments with pea plants in the 1860s. His work established the laws of inheritance, though it was not recognised until after his death."},
            {"question": "Which vitamin is synthesised by human skin on exposure to sunlight?", "options": {"A": "Vitamin A", "B": "Vitamin B12", "C": "Vitamin C", "D": "Vitamin D"}, "answer": "D", "explanation": "Vitamin D (calciferol) is produced in the skin when exposed to ultraviolet B (UVB) radiation from sunlight. It is essential for calcium absorption and bone health."},
            {"question": "Which part of the brain is responsible for balance and coordination of movement?", "options": {"A": "Cerebrum", "B": "Medulla Oblongata", "C": "Thalamus", "D": "Cerebellum"}, "answer": "D", "explanation": "The cerebellum, located at the back of the brain, coordinates voluntary movements and maintains balance and posture. Damage to the cerebellum results in poor coordination and unsteady movement."},
            {"question": "During which phase of the cell cycle does DNA replication occur?", "options": {"A": "G1 Phase", "B": "S Phase (Synthesis)", "C": "G2 Phase", "D": "M Phase (Mitosis)"}, "answer": "B", "explanation": "DNA replication occurs during the Synthesis (S) phase of the cell cycle interphase. During this phase, the cell duplicates its entire genome so that both daughter cells receive a complete copy."},
        ],
        "Hard": [
            {"question": "Which enzyme unwinds the DNA double helix during replication?", "options": {"A": "DNA Polymerase", "B": "DNA Ligase", "C": "Helicase", "D": "Primase"}, "answer": "C", "explanation": "Helicase is the enzyme that unwinds and separates the two strands of the DNA double helix at the replication fork by breaking hydrogen bonds between base pairs. This exposes the template strands for replication."},
            {"question": "Which metabolic pathway converts glucose into pyruvate in the cytoplasm?", "options": {"A": "Krebs Cycle", "B": "Calvin Cycle", "C": "Oxidative Phosphorylation", "D": "Glycolysis"}, "answer": "D", "explanation": "Glycolysis is the metabolic pathway that breaks down one molecule of glucose into two molecules of pyruvate, occurring in the cytoplasm. It produces a net gain of 2 ATP molecules and 2 NADH molecules."},
            {"question": "The lac operon model of gene regulation was proposed by:", "options": {"A": "Watson and Crick", "B": "Jacob and Monod", "C": "Beadle and Tatum", "D": "Avery, MacLeod and McCarty"}, "answer": "B", "explanation": "Francois Jacob and Jacques Monod proposed the lac operon model in 1961 to explain how gene expression is regulated in E. coli in response to lactose availability. They were awarded the Nobel Prize in 1965."},
            {"question": "Which type of immunity involves memory B and T cells for long-term protection?", "options": {"A": "Innate Immunity", "B": "Passive Immunity", "C": "Adaptive (Acquired) Immunity", "D": "Non-specific Immunity"}, "answer": "C", "explanation": "Adaptive immunity is characterised by specificity and memory. After an infection or vaccination, memory B and T cells persist and enable a faster, stronger response upon re-exposure to the same pathogen."},
            {"question": "The Hardy-Weinberg principle states that in a large, randomly mating population:", "options": {"A": "Natural selection always changes allele frequencies", "B": "Mutation rates increase over time", "C": "Allele and genotype frequencies remain constant over generations", "D": "Predator-prey ratios stabilise"}, "answer": "C", "explanation": "The Hardy-Weinberg equilibrium states that allele and genotype frequencies in a population remain stable from generation to generation in the absence of disturbing factors like mutation, selection, and genetic drift."},
        ],
    },
    "Computer Science": {
        "Easy": [
            {"question": "What does CPU stand for?", "options": {"A": "Computer Personal Unit", "B": "Central Processing Unit", "C": "Central Program Utility", "D": "Core Processing Unit"}, "answer": "B", "explanation": "CPU stands for Central Processing Unit, which is the primary component of a computer that executes instructions. It performs arithmetic, logic, control, and input/output operations."},
            {"question": "Which programming language category is closest to human-readable language?", "options": {"A": "Machine language", "B": "Assembly language", "C": "High-level language", "D": "Binary code"}, "answer": "C", "explanation": "High-level programming languages (like Python, Java, C++) use syntax closer to natural human language and are machine-independent. They must be compiled or interpreted into machine code for execution."},
            {"question": "What does HTML stand for?", "options": {"A": "High Transfer Markup Language", "B": "HyperText Management Language", "C": "HyperText Markup Language", "D": "Home Tool Markup Language"}, "answer": "C", "explanation": "HTML (HyperText Markup Language) is the standard markup language used to create web pages. It defines the structure and content of a webpage using elements represented by tags."},
            {"question": "What is the binary representation of the decimal number 10?", "options": {"A": "1000", "B": "0110", "C": "1100", "D": "1010"}, "answer": "D", "explanation": "Decimal 10 in binary is 1010. This is calculated as: 1x8 + 0x4 + 1x2 + 0x1 = 10. Binary uses only two digits (0 and 1) and each position represents a power of 2."},
            {"question": "What is the output of the Python expression: 2 ** 3?", "options": {"A": "6", "B": "5", "C": "9", "D": "8"}, "answer": "D", "explanation": "In Python, ** is the exponentiation operator. So 2 ** 3 means 2 raised to the power 3, which equals 2 x 2 x 2 = 8."},
        ],
        "Medium": [
            {"question": "What is the time complexity of binary search on a sorted array?", "options": {"A": "O(n)", "B": "O(n squared)", "C": "O(log n)", "D": "O(1)"}, "answer": "C", "explanation": "Binary search has a time complexity of O(log n) because it repeatedly divides the search space in half. With each comparison, the algorithm eliminates half the remaining elements."},
            {"question": "Which data structure follows the LIFO (Last In, First Out) principle?", "options": {"A": "Queue", "B": "Array", "C": "Linked List", "D": "Stack"}, "answer": "D", "explanation": "A stack follows the LIFO principle, meaning the last element added is the first to be removed. It supports two main operations: push (add to top) and pop (remove from top)."},
            {"question": "What does SQL stand for?", "options": {"A": "Simple Query Language", "B": "Structured Query Language", "C": "Standard Question Logic", "D": "Sequential Query Language"}, "answer": "B", "explanation": "SQL (Structured Query Language) is a domain-specific language used to manage and query relational databases. It supports operations like SELECT, INSERT, UPDATE, DELETE, and more."},
            {"question": "Which HTTP method is primarily used to send data to a server (e.g., form submission)?", "options": {"A": "GET", "B": "POST", "C": "PUT", "D": "DELETE"}, "answer": "B", "explanation": "The HTTP POST method sends data to the server in the request body, commonly used for form submissions or creating resources. Unlike GET, POST requests are not cached and not stored in browser history."},
            {"question": "What is the primary role of a compiler in programming?", "options": {"A": "Runs programs directly line by line", "B": "Manages computer memory allocation", "C": "Translates high-level source code to machine code", "D": "Connects programs to the internet"}, "answer": "C", "explanation": "A compiler translates the entire source code written in a high-level language into machine code (binary) before execution. Unlike an interpreter, a compiler processes the whole program at once."},
        ],
        "Hard": [
            {"question": "What is the worst-case time complexity of the QuickSort algorithm?", "options": {"A": "O(n log n)", "B": "O(n)", "C": "O(log n)", "D": "O(n squared)"}, "answer": "D", "explanation": "QuickSort has a worst-case time complexity of O(n squared), which occurs when the pivot is always chosen as the smallest or largest element. Its average case is O(n log n)."},
            {"question": "In networking, what does CIDR stand for?", "options": {"A": "Circuit-based Internet Data Routing", "B": "Common Interface Domain Registry", "C": "Classless Inter-Domain Routing", "D": "Centralized Internet Data Relay"}, "answer": "C", "explanation": "CIDR (Classless Inter-Domain Routing) is a method for allocating IP addresses and routing. It replaced the old class-based system and uses prefix notation (e.g., 192.168.1.0/24) to specify network and host portions."},
            {"question": "Which design pattern ensures that only one instance of a class is created throughout an application?", "options": {"A": "Factory Pattern", "B": "Observer Pattern", "C": "Singleton Pattern", "D": "Decorator Pattern"}, "answer": "C", "explanation": "The Singleton pattern restricts the instantiation of a class to a single object and provides a global point of access to it. It is commonly used for database connections, logging, or configuration management."},
            {"question": "In relational databases, what does ACID stand for?", "options": {"A": "Access, Control, Integrity, Data", "B": "Atomic, Compound, Index, Domain", "C": "Atomicity, Consistency, Isolation, Durability", "D": "Algorithm, Cache, Input, Dynamic"}, "answer": "C", "explanation": "ACID is a set of properties that guarantee database transactions are processed reliably: Atomicity (all or nothing), Consistency (valid state), Isolation (concurrent transactions don't interfere), Durability (committed data persists)."},
            {"question": "What is the primary purpose of a mutex in concurrent programming?", "options": {"A": "To increase processing speed", "B": "To automatically prevent all deadlocks", "C": "To manage creation of new threads", "D": "To ensure mutual exclusion when accessing shared resources"}, "answer": "D", "explanation": "A mutex (mutual exclusion object) ensures that only one thread can access a shared resource at a time. When a thread acquires the mutex lock, other threads must wait, preventing race conditions."},
        ],
    },
    "English": {
        "Easy": [
            {"question": "Which of the following words is a noun?", "options": {"A": "Run", "B": "Quickly", "C": "Beautiful", "D": "Happiness"}, "answer": "D", "explanation": "A noun is a word that names a person, place, thing, or abstract idea. 'Happiness' is an abstract noun. 'Run' is a verb, 'quickly' is an adverb, and 'beautiful' is an adjective."},
            {"question": "What is the correct plural form of the word 'child'?", "options": {"A": "Childs", "B": "Childes", "C": "Childrens", "D": "Children"}, "answer": "D", "explanation": "The plural of 'child' is 'children', which is an irregular plural form. Unlike regular nouns that simply add -s or -es, 'children' is formed from the Old English word 'cildru'."},
            {"question": "Identify the sentence written in the passive voice:", "options": {"A": "She writes a letter every day.", "B": "They are writing letters now.", "C": "The letter was written by her.", "D": "Write the letter now!"}, "answer": "C", "explanation": "In the passive voice, the subject receives the action rather than performing it. 'The letter was written by her' — the subject 'letter' is acted upon, making it passive."},
            {"question": "Which word is a synonym of 'happy'?", "options": {"A": "Sad", "B": "Tired", "C": "Angry", "D": "Joyful"}, "answer": "D", "explanation": "A synonym is a word with the same or similar meaning. 'Joyful' means feeling great happiness and delight, making it the closest synonym to 'happy' among the options."},
            {"question": "In the sentence 'The tall boy ran fast', which word is an adjective?", "options": {"A": "boy", "B": "ran", "C": "fast", "D": "tall"}, "answer": "D", "explanation": "An adjective modifies or describes a noun. In this sentence, 'tall' describes the noun 'boy', making it an adjective. 'Fast' here is an adverb modifying the verb 'ran'."},
        ],
        "Medium": [
            {"question": "Which figure of speech is used in the phrase 'The wind whispered through the trees'?", "options": {"A": "Simile", "B": "Metaphor", "C": "Hyperbole", "D": "Personification"}, "answer": "D", "explanation": "Personification attributes human characteristics to non-human things. Saying the wind 'whispered' gives it a human quality. A simile compares using 'like/as', a metaphor directly equates two things."},
            {"question": "What is the antonym of 'benevolent'?", "options": {"A": "Kind", "B": "Generous", "C": "Malevolent", "D": "Charitable"}, "answer": "C", "explanation": "'Benevolent' means well-meaning and kindly. Its antonym is 'malevolent', which means having or showing a wish to do evil to others. Both words share the Latin root 'volent' (wishing)."},
            {"question": "In which tense is the sentence: 'She has been working here for five years'?", "options": {"A": "Simple Present", "B": "Present Perfect", "C": "Past Perfect Continuous", "D": "Present Perfect Continuous"}, "answer": "D", "explanation": "The Present Perfect Continuous tense is used for actions that started in the past and continue up to now. It is formed with 'have/has been + present participle (verb+ing)'."},
            {"question": "What does the word 'ubiquitous' mean?", "options": {"A": "Extremely rare", "B": "Outdated or old-fashioned", "C": "Unique and one of a kind", "D": "Present or appearing everywhere"}, "answer": "D", "explanation": "'Ubiquitous' comes from Latin 'ubique' meaning 'everywhere'. It describes something that seems to appear everywhere simultaneously, for example: 'Smartphones have become ubiquitous in modern life.'"},
            {"question": "What is a 'gerund' in English grammar?", "options": {"A": "A verb used as an adjective", "B": "An adverb that modifies a noun", "C": "A noun formed from a verb by adding -ing", "D": "A conjunction joining two clauses"}, "answer": "C", "explanation": "A gerund is the -ing form of a verb used as a noun. For example, in 'Swimming is good exercise', 'swimming' functions as the subject noun. Gerunds can serve as subjects, objects, or complements."},
        ],
        "Hard": [
            {"question": "Which sentence is grammatically correct?", "options": {"A": "Each of the students have submitted their work.", "B": "Each students has submitted their work.", "C": "Every students have submitted work.", "D": "Each of the students has submitted their work."}, "answer": "D", "explanation": "'Each' is an indefinite pronoun that takes a singular verb. Therefore, 'Each of the students has submitted their work' is correct. The plural noun 'students' in the prepositional phrase does not affect subject-verb agreement."},
            {"question": "The rhetorical device where the last word or phrase of one clause becomes the first of the next is called:", "options": {"A": "Anaphora", "B": "Epistrophe", "C": "Chiasmus", "D": "Anadiplosis"}, "answer": "D", "explanation": "Anadiplosis involves repeating the last word of one clause at the start of the next, e.g., 'Fear leads to anger. Anger leads to hate.' Anaphora is repetition at the beginning; epistrophe at the end."},
            {"question": "Which sentence contains a dangling modifier?", "options": {"A": "Walking through the park, she saw the flowers.", "B": "After reading the book, he wrote a review.", "C": "Singing loudly, the child played in the yard.", "D": "Having finished dinner, the table was cleared."}, "answer": "D", "explanation": "A dangling modifier is a word or phrase that modifies a word not clearly stated in the sentence. In option D, 'Having finished dinner' implies the table finished dinner. It should read: 'Having finished dinner, they cleared the table.'"},
            {"question": "What does the word 'prolix' mean?", "options": {"A": "Brief and to the point", "B": "Extremely precise and accurate", "C": "Using too many words; long-winded", "D": "Cryptic and difficult to understand"}, "answer": "C", "explanation": "'Prolix' (from Latin 'prolixus', meaning 'extended') describes speech or writing that uses too many words and is tediously long. Its antonym is 'concise' or 'succinct'."},
            {"question": "In grammar, a 'pleonasm' refers to:", "options": {"A": "A word that modifies a verb", "B": "A form of indirect reported speech", "C": "A type of conditional clause structure", "D": "The use of more words than necessary to express an idea"}, "answer": "D", "explanation": "A pleonasm is the use of redundant words that add no meaning, such as 'free gift', 'past history', or 'advance warning'. While sometimes considered poor style, pleonasms are occasionally used for emphasis."},
        ],
    },
}